name: Test new feature

on:
  push:
    branches:
      - feature/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run all tests
      run: |
        python -m unittest tests/*.py
